### PR TITLE
fix: add base64-es5.js into package

### PR DESCRIPTION
**Pull request by JounQin**
specify files included into npm

### CODE REVIEW

**Comment by dankogai** [comment]
I am not sure including  `base64-es5.js` is a good idea but I would like to merge the rest of it, especially spell-checking.  So here is what I am going to do.

0. merge this PR
1. remove `base64-es5.js` from the repository for the time being.

Please make a PR dedicated to this issue next time.

**Comment by JounQin** [comment]
I don't understand why `base64-es5.js` should not be included, it would easier to use directly in an ES5 environment. Or I don't understand why script `transpile` exists, if the user wants to transpile ES6 codes manually, there would be a lot of tools to use instead of cloning and running this script arduously.

Of course, it could be added into `.gitignore` to be excluded from repository.

**Comment by dankogai** [comment]
The whole point of version 3 is to make it harder, not easier, to be used from ES5 environments.  And transpilers are not as compatible with target environments as minifiers.  I should have `transpile` option dropped instead.

**Comment by JounQin** [comment]
Yes, that's my point, so should `transpile` be removed from `package.json`?

**Comment by dankogai** [comment]
Done.  It is already removed from `README.md`.

**Pull request merged**
