### PR TITLE
minor fix in tsconfig.json

### PR DESCRIPTION
**Pull request by loone96**
Minor fix in tsconfig.json file because it didn't properly compiles into ES2015.

Test passed checked.

### CODE REVIEW

**Comment by dankogai** [comment]
Thank you!  Since the resulting `.{mjs,js}` remains the same I am not upgrading the version.

**Comment by loone96** [comment]
My bad. I didn't push with typescript compiling because I thought CI/CD will do it.

Since I upload typescript compiler options, it should be re-compiled. For example 

`const b64tab = ((a) => {
    let tab = {};
    a.forEach((c, i) => tab[c] = i);
    return tab;
})(b64chs);`

Anonymous function b64tab will be changed to ES5 if you compile again.

**Comment by dankogai** [comment]
Take it easy.  `b64tab` is *not* an anonymous function.  it is an object which maps characters to integers (`Number`).

```javascript
const b64tab // object
  =   ( // anonymous function
    (a) => { let tab = {}; a.forEach((c, i) => tab[c] = i); return tab; }
  )(
      b64chs // argument (string)
  );
```

I also made sure the resulting `.{mjs,js}` remains the same by `make clean` (deletes .mjs and js) and `make test`.

**Comment by loone96** [comment]
Sorry. I meant 'arrow function'.

**Pull request merged**
