### PR TITLE
Fix: #61 Make this lib support es6 module

### PR DESCRIPTION
**Pull request by ufolux**

### CODE REVIEW

**Comment by ufolux** [comment]
@dankogai pls check this pr

**Comment by dankogai** [comment]
`test/es6.js` is causing travis to fail. **I WILL NOT MERGE TILL TRAVIS IS HAPPY**.

**Comment by ufolux** [comment]
@dankogai It's ready for you to merge

**Comment by dankogai** [comment]
Thank you!

**Comment by ufolux** [comment]
(-:

**Pull request merged**
